List<String> questionsList = [
  'Do you have investments? What type',
  'Do you have ledger?',
  'Do you have Safe?',
  'Is there a key and where it would be?',
  'Who get your jewelry?',
  'Who would you like to go through your cloths? Donate?',
  'Who gets your shoes? Donate?',
  'Is your car paid off?',
  'Keep kids away from.',
  'Kids should go to',
  'Do you have insurance with your employer?',
  'Is your home paid for?',
  'Do you keep important documents somewhere?',
  'Credit Cards? , Subscription? , Storage?',
  'Any app you want deleted from your phone?',
  'Keep your social media profile up?, cremated? ',
  'Spread ashes where? ',
  'If buried do you want people to visit you?',
  'Message on Headstone, QR code and video?',
  'Any cash somewhere?',
  'Who gets Electronics?',
  'Furniture? Donate?',
  'Banks?',
];
